const $=s=>document.querySelector(s);let settings=null,products=[],pendingPayload=null;
function receive(){return document.querySelector('input[name="receive"]:checked').value}function product(){return products.find(p=>p.id===$("#product").value)}
function fee(sub){if(!settings||receive()!=="delivery")return 0;if(settings.free_shipping_threshold&&sub>=settings.free_shipping_threshold)return 0;return Number(settings.shipping_fee||0)}
function estimate(){const p=product(),q=Math.max(1,Number($("#quantity").value||1));if(!p)return;$("#estimate").value=Hangwa.formatMoney(Number(p.price)*q+fee(Number(p.price)*q))}
function address(){const d=receive()==="delivery";$("#address-field").hidden=!d;$("#address").required=d;if(!d)$("#address").value="";estimate()}
async function load(){if(!window.supabaseConfigured)return;const db=window.supabaseClient,[s,p]=await Promise.all([db.from("store_settings").select("*").eq("id",1).single(),db.from("products").select("*").eq("active",true).order("sort_order")]);if(s.error||p.error)return;settings=s.data;products=p.data||[];const t=Hangwa.koreaToday(),open=!settings.sale_force_closed&&settings.sale_start&&settings.sale_end&&t>=settings.sale_start&&t<=settings.sale_end;$("#sale-banner").innerHTML=`<strong>${open?(settings.sale_title||"예약판매 접수 중"):(settings.sale_force_closed?"예약판매 조기 종료":"현재 예약판매 기간이 아닙니다.")}</strong><p>${open?`${Hangwa.formatDate(settings.sale_start)} ~ ${Hangwa.formatDate(settings.sale_end)} · 재고 소진 시 조기 종료될 수 있습니다.`:(settings.sale_force_closed?(settings.sale_closed_reason||"품절 등으로 예약판매가 종료되었습니다."):`예약기간: ${Hangwa.formatDate(settings.sale_start)} ~ ${Hangwa.formatDate(settings.sale_end)}`)}</p>`;$("#order-area").hidden=!open;$("#closed-area").hidden=open;if(!open)$("#closed-copy").textContent=settings.sale_force_closed?(settings.sale_closed_reason||"예약판매가 종료되었습니다."):"다음 예약판매 일정을 확인해 주세요.";$("#product").innerHTML="";products.forEach(p=>{const sold=p.stock!==null&&p.stock<=0,o=document.createElement("option");o.value=p.id;o.disabled=sold;o.textContent=`${p.weight} · ${Hangwa.formatMoney(p.price)}${sold?" · 품절":""}`;$("#product").appendChild(o)});$("#bank-box").innerHTML=`<h3>무통장입금</h3><p>${[settings.bank_name,settings.account_number,settings.account_holder].filter(Boolean).join(" · ")||"계좌정보 준비 중"}</p><p>주문 접수 후 입금해 주세요.</p>`;estimate()}
function payload(){const p=product(),q=Math.max(1,Number($("#quantity").value||1)),r=receive();return{product:p,quantity:q,receive:r,api:{p_product_id:p.id,p_quantity:q,p_customer_name:$("#customer-name").value.trim(),p_phone:$("#phone").value.trim(),p_receive:r,p_address:r==="delivery"?$("#address").value.trim():"",p_depositor_name:$("#depositor").value.trim(),p_request:$("#request").value.trim(),p_refund_bank:$("#refund-bank").value.trim(),p_refund_account:$("#refund-account").value.trim(),p_refund_holder:$("#refund-holder").value.trim(),p_privacy_agreed:$("#privacy-agree").checked}}}
$("#order-form").addEventListener("submit",e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;pendingPayload=payload();const sub=pendingPayload.product.price*pendingPayload.quantity,rows=[["상품",pendingPayload.product.weight],["수량",`${pendingPayload.quantity}개`],["주문자",pendingPayload.api.p_customer_name],["전화번호",pendingPayload.api.p_phone],["수령방법",pendingPayload.receive==="delivery"?"배송":"픽업"],...(pendingPayload.receive==="delivery"?[["배송지",pendingPayload.api.p_address]]:[]),["입금자명",pendingPayload.api.p_depositor_name],["총금액",Hangwa.formatMoney(sub+fee(sub))]];$("#confirm-summary").innerHTML=rows.map(([k,v])=>`<dt>${k}</dt><dd>${v}</dd>`).join("");Hangwa.openModal("confirm-modal")});
$("#final-submit").addEventListener("click",async()=>{if(!pendingPayload)return;const b=$("#final-submit");b.disabled=true;b.textContent="접수 중...";const{data,error}=await window.supabaseClient.rpc("create_public_order",pendingPayload.api);b.disabled=false;b.textContent="최종 주문";if(error){Hangwa.toast(error.message||"주문 접수 실패");return}const row=Array.isArray(data)?data[0]:data;Hangwa.closeModal("confirm-modal");$("#success-order-number").textContent=row.order_number;$("#success-total").textContent=`총 결제금액 ${Hangwa.formatMoney(row.total_price)}`;$("#success-lookup").href=`../lookup/?order=${encodeURIComponent(row.order_number)}&phone=${encodeURIComponent(pendingPayload.api.p_phone)}`;Hangwa.openModal("success-modal");$("#order-form").reset();address();pendingPayload=null});
$("#product").addEventListener("change",estimate);$("#quantity").addEventListener("input",estimate);document.querySelectorAll('input[name="receive"]').forEach(r=>r.addEventListener("change",address));$("#order-form").addEventListener("reset",()=>setTimeout(()=>{address();estimate()},0));load();